# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish and Release

# on:
#   release:
#     types: [published]

on: 
  push:
    branches:
      - main

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      # - run: npm ci
      - run: yarn install
      - run: yarn build
      - run: yarn test --passWithNoTests

  bump-version:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
        # - name: Test
        # run: echo  ${{ toJson(github.event) }}
      - name: Read release type
        if: ${{ contains(github.event.label.name, 'minor')}}
        run: echo "release_type=minor" >> "$GITHUB_ENV"
      - name: Check for minor
        if: ${{ contains(github.event.label.name, 'major')}}
        run: echo "release_type=major" >> "$GITHUB_ENV"
      - name: Check for major
        if: ${{ !env.release_type }}
        run: echo "release_type=patch" >> "$GITHUB_ENV"
        # run: |
        #   if [[ github.event.label.name == 'release:minor' ]]; then
        #       echo "release_type=minor" >> "$GITHUB_ENV"
        #   else if [[ github.event.label.name == 'release:major' ]]; then
        #       echo "release_type=major" >> "$GITHUB_ENV"
        #   else 
        #       echo "release_type=patch" >> "$GITHUB_ENV"
        #   fi
      - name: Setup GIT
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
      - name: Bump version
        run: |
          yarn install
          yarn --no-git-tag-version version --${{ env.release_type }} -m "Auto bump version to %s"
          yarn publish
          git commit -a -m "Auto bump version"
          git push https://${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY $GITHUB_REF_NAME
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          
  publish-gpr:
    needs: bump-version
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      repository-projects: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      # - run: npm ci
      - run: yarn install
      - run: yarn build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  release-gh:
    needs:  publish-gpr
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_ACC_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
